
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    url: url
    password: pw

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

  mail:
    host: smtp.naver.com
    port: 465
    username: username
    password: password
    properties:
      protocol: smtp
      debug: true
      stmp:
        auth: true
        starttls:
          enable: true
        ssl:
          enable: true
          trust: smtp.naver.com
  profiles:
    include:
      - secretfile

encrypt:
  secret_key: secretKey
  aes_alg: algorithm

server:
  port: 8081