openapi: 3.0.0
servers:
  - url: 'http://localhost:8080'
info:
  description: 계정 컨트롤러
  version: 1.0.0
  title: account
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: account
    description: 계정
paths: # 아래로 API Path를 명시한다
  '/api/account/{signupId}': # /test API에 대한 명세
    post: # HTTP get Method를 사용한다.
      operationId: createAccount
      tags:
        - account
      summary: 계정 생성 # 설명
      security: # 인증정보를 표현한다.
        - cookieAuth: [ ] # 쿠키를 이용한 인증정보 (위에서 정의한 인증정보)
      parameters:
        - in: path
          name: signupId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: 계정 생성 request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountCreateRequest'

      responses:
        '200': # HTTP Status Code
          description: 요청 성공
#          content: # 응답값
#            application/json:
#              schema:
#                properties:
#                  hello:
#                    type: string
#                    example: world
#                  hello2:
#                    type: string
#                    example: world2



components:
  schemas:
    AccountCreateRequest:
      title: 'AccountCreateRequest'
      description: '계정 생성 reuqest body'
      properties: # 필드값
        password:
          type: string
          pattern: '[a-zA-Z0-9]{6,12}'
          description: "비밀번호는 영어와 숫자를 포함한 6~12자리 이내로 입력해주세요."
          example: swee344
        name:
          type: string
          minLength: 2
          maxLength: 16
          example: swee344