openapi: 3.0.0
servers:
  - url: 'http://signup.swagger.io/v3'
info:
  description: 회원가입 컨트롤러
  version: 1.0.0
  title: signup
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: signUp
    description: 회원가입
paths: # 아래로 API Path를 명시한다
  '/api/signup': # /test API에 대한 명세
    post: # HTTP get Method를 사용한다.
      operationId: signup
      tags:
        - signUp
      summary: 회원가입 # 설명
      security: # 인증정보를 표현한다.
        - cookieAuth: [ ] # 쿠키를 이용한 인증정보 (위에서 정의한 인증정보)
      requestBody:
        description: 회원 가입 request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'

      responses:
        '200': # HTTP Status Code
          description: 요청 성공
#          content: # 응답값
#            application/json:
#              schema:
#                properties:
#                  hello:
#                    type: string
#                    example: world
#                  hello2:
#                    type: string
#                    example: world2



components:
  schemas:
    SignupRequest:
      title: 'SignupRequest'
      description: '가입 요청 reuqest body'
      properties: # 필드값
        email:
          type: string
          pattern: '^[a-zA-Z0-9+-\_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
          example: gusals@naver.com